; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
include_dir = Core/Inc
src_dir = Core/Src

[env:genericSTM32F103RC]
platform = ststm32
board = genericSTM32F103RC
framework = stm32cube
; force inclusion of lib/FreeRTOS
lib_deps = FreeRTOS

upload_protocol = stlink
debug_tool = stlink

build_type = debug
build_flags =
    -Wall ; Treat all warnings as errors
    -Wl,--undefined,_printf_float ; Enable %f in printf
    -ICore/Src/Middlewares/Third_Party/FreeRTOS/Source/include
    -ICore/Src/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM3
    -ICore/Src/Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang
    -ICore/Src/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2


    ; -IMiddlewares/Third_Party/FreeRTOS/Source/include
    ; -IMiddlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM3
    ; -IMiddlewares/Third_Party/FreeRTOS/Source/portable/MemMang
    ; -IMiddlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2

monitor_speed = 115200