name: Battery Management System (BMS) CI

# Controls when the workflow will run
on:
  # Trigger the workflow on push but only for changes to relevant files
  push:
    paths:
      - 'components/bms/bms_master/**'
      - '.github/workflows/bms_master.yml'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      
      - name: Build PlatformIO Project
        run: pio run
        working-directory: components/bms/bms_master

      - name: Get branch name and commit hash
        run: |
          echo "commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV


      - name: Collect Build Artifacts
        run: |
          mkdir build
          cp components/bms/bms_master/.pio/build/genericSTM32F103RC/firmware.elf build/bms-${{ env.commit_hash }}.elf

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-bms-${{ env.commit_hash }}
          path: build