name: Build Components

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build TEL
        uses: xanderhendriks/action-build-stm32cubeide@v13.0
        with:
          project-path: '../../components/tel'
          project-target: 'tel'