name: Build Components

on:
  pull_request:
    paths:
      - 'components/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        component: [tel]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '8'

      - name: Build ${{ matrix.component }}
        uses: xanderhendriks/action-build-stm32cubeide@v15.0
        with:
          project-path: components/${{ matrix.component }}
          project-target: ${{ matrix.component }}

      - name: Verify ELF Files Before Upload
        run: ls -l components/${{ matrix.component }}/Release/*.elf

      - name: Upload ELF artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.component }}-elf
          path: components/${{ matrix.component }}/Release/*.elf

      - name: List build outputs
        run: ls -R components/${{ matrix.component }}/Release