name: Build Components

on:
  pull_request:
    paths:
      - 'components/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        component: [tel]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '8'

      - name: Build ${{ matrix.component }}
        uses: xanderhendriks/action-build-stm32cubeide@v15.0
        with:
          project-path: components/${{ matrix.component }}
          project-target: ${{ matrix.component }}

      - name: Verify ELF Files Before Upload
        run: ls -l components/${{ matrix.component }}/Release/*.elf
        
      - name: Upload ELF artifact to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --follow-symlinks --exact-timestamps
        env:
          AWS_S3_BUCKET: your-bucket-name
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: components/${{ matrix.component }}/Release/
          DEST_DIR: ${{ matrix.component }}/
        
      - name: List build outputs
        run: ls -R components/${{ matrix.component }}/Release