name: Build Components

on: [pull_request]

jobs:
  build_components:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.1.0

      # #----- TEL -----#
      # - name: Build TEL
      #   uses: xanderhendriks/action-build-stm32cubeide@v15.0
      #   with:
      #     project-path: 'components/tel'
      #     project-target: 'tel'

      #----- DRD -----#
      - name: Build DRD
        uses: xanderhendriks/action-build-stm32cubeide@v13.0
        with:
          project-path: 'components/drd'
          project-target: 'drd'

      #----- STR -----#
      - name: Build STR
        uses: xanderhendriks/action-build-stm32cubeide@v13.0
        with:
          project-path: 'components/str'
          project-target: 'str'

      #----- MDI -----#
      - name: Build MDI
        uses: xanderhendriks/action-build-stm32cubeide@v13.0
        with:
          project-path: 'components/mdi'
          project-target: 'mdi'
